import ChatItem from "./chat_item"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ChatItem,
  "https://www.figma.com/design/tRrON1W9zWZucj8wMZV8II/%E2%9B%94%EF%B8%8F-DO-NOT-USE-Mashlat-Design-System?node-id=10866%3A12786",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      title: figma.string("title ✏️"),
      icon: figma.instance("icon 🔄"),
      // No matching props could be found for these Figma properties:
      // "icon": figma.instance('icon 🔄'),
      // "title": figma.string('title ✏️'),
      "description": figma.string('description ✏️'),
      // "state": figma.enum('state', {
      //   "idle": "idle",
      //   "hover": "hover"
      // })
    },
    example: (props: any) => <ChatItem
      title={props.title}
      subtitle={props.description}
      icon={props.icon}
    />,
  },
)
